-- Staged view for CBA_CI (typed casts only)
CREATE OR REPLACE TEMPORARY VIEW CBA_CI_VS AS
SELECT
  CI_ID,
  DOB,
  EMAIL
FROM (
  SELECT
    CAST(JSON_VALUE(payload, '$.CI_ID') AS BIGINT) AS CI_ID,
    CAST(JSON_VALUE(payload, '$.DOB') AS DATE) AS DOB,
    CAST(JSON_VALUE(payload, '$.EMAIL') AS VARCHAR(256)) AS EMAIL
  FROM RAW_EVENTS
  WHERE table_name = 'CBA_CI'
) t;


-- Staged view for CBA_CI_ADR (typed casts only)
CREATE OR REPLACE TEMPORARY VIEW CBA_CI_ADR_VS AS
SELECT
  CI_ID,
  ADDR_LINE1,
  STATE,
  CITY,
  ZIP,
  COUNTRY
FROM (
  SELECT
    CAST(JSON_VALUE(payload, '$.CI_ID') AS BIGINT) AS CI_ID,
    CAST(JSON_VALUE(payload, '$.ADDR_LINE1') AS VARCHAR(200)) AS ADDR_LINE1,
    CAST(JSON_VALUE(payload, '$.STATE') AS VARCHAR(2)) AS STATE,
    CAST(JSON_VALUE(payload, '$.CITY') AS VARCHAR(120)) AS CITY,
    CAST(JSON_VALUE(payload, '$.ZIP') AS VARCHAR(20)) AS ZIP,
    CAST(JSON_VALUE(payload, '$.COUNTRY') AS VARCHAR(2)) AS COUNTRY
  FROM RAW_EVENTS
  WHERE table_name = 'CBA_CI_ADR'
) t;


-- Staged view for CBA_CI_XREF (typed casts only)
CREATE OR REPLACE TEMPORARY VIEW CBA_CI_XREF_VS AS
SELECT
  CI_ID,
  XREF_TYPE
FROM (
  SELECT
    CAST(JSON_VALUE(payload, '$.CI_ID') AS BIGINT) AS CI_ID,
    CAST(JSON_VALUE(payload, '$.XREF_TYPE') AS VARCHAR(20)) AS XREF_TYPE
  FROM RAW_EVENTS
  WHERE table_name = 'CBA_CI_XREF'
) t;
