INSERT INTO CBA_CI_ADR_FGAC
SELECT
  CBA_CI_ADR_VS.CI_ID AS CI_ID,
  CBA_CI_VS.DOB AS DOB,
  TRIM(CBA_CI_ADR_VS.ADDR_LINE1) AS ADDR_LINE1,
  CBA_CI_ADR_VS.STATE AS STATE,
  CBA_CI_XREF_VS.XREF_TYPE AS XREF_TYPE,
  UPPER(CBA_CI_ADR_VS.CITY) AS CITY,
  SUBSTRING(REGEXP_REPLACE(CBA_CI_ADR_VS.ZIP, '[^0-9]', ''), 1, 5) AS ZIP5,
  COALESCE(CBA_CI_ADR_VS.COUNTRY, 'US') AS COUNTRY,
  COALESCE(LOWER(COALESCE(CBA_CI_VS.EMAIL, '')), '') AS EMAIL_LOWER
FROM CBA_CI_ADR_VS
LEFT JOIN CBA_CI_VS ON CBA_CI_VS.CI_ID = CBA_CI_ADR_VS.CI_ID
LEFT JOIN CBA_CI_XREF_VS ON CBA_CI_XREF_VS.CI_ID = CBA_CI_VS.CI_ID;
